### ISSUE TITLE
O que é o EXPO?

### ISSUE THREAD

**Issue by josenaves** [react-native-drops/react-native-faq#1]
Gostaria de entender melhor o que é o EXPO e qual a diferença entre o React Native tradicional.

**Comment by josenaves** [comment]
O que você quis dizer com React Native tradicional?

**Comment by rafaellincoln** [comment]
A grande diferença entre EXPO e React Native é que o EXPO não utiliza código nativo Android e IOS, todo o código de um APP EXPO fica no "host", que é o APP da Expo que precisa estar instalado no Smartphone. Com isso você não precisa de ter um ambiente configurado com Android Studio e XCode para criar um APP para Android e IOS. A grande desvantagem do EXPO em relação ao React Native é que por ele não utilizar código nativo, apenas o que está no app "host" Expo, você fica limitado as libs que estão disponíveis no app da Expo, alem de ter uma camada a mais de comunicação com o código nativo.

**Vantagens EXPO**
- Comece a desenvolver mais rápido.
- Faça um APP para IOS sem a necessidade de um MAC.

**Desvantagens EXPO***
- Tenha controle sobre seus builds.
- Fique a vontade para adicionar e criar suas propiás libs Nativas.

**Conclusão**
Ao iniciar o desenvolvimento de um APP você analisar qual a melhor opção para você, se você está iniciando com o desenvolvimento Mobile e quer desenvolver um aplicativo de forma rápida, sem ter que configurar um ambiente para cada plataforma e não tem 5k sobrando pra comprar um MAC, eu recomendo utilizar o EXPO. Agora se está construindo um APP complexo e que necessite muita performance e vários componentes diferentes eu te recomendo utilizar o React Native. Então você deve utiliza-los de acordo com a sua necessidade, você deve decidir se as vantagens compensam as desvantagens e então utilizar o CRNA ou o react-native-cli.

**Comment by josenaves** [comment]
Página publicada no FAQ

**Comment by josenaves** [comment]
https://github.com/react-native-drops/react-native-faq/wiki/Expo
