### ISSUE TITLE
react-native no android < 5

### ISSUE THREAD

**Issue by allefgomes** [react-native-drops/react-native-faq#8]
Existe alguma solução para emular o projeto `react-native init` em android que seja abaixo do 5?

Porque é necessário conforme a documentação que o android tenha `adb reverse` e os < 5 não tem...

Grato pela ajuda desde já.

**Comment by josenaves** [comment]
Não sei se entendi direito - a documentação oficial do React Native diz isso:

> Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.

https://github.com/facebook/react-native

**Comment by josenaves** [comment]
Você precisa usar adb reverse ? Por que ? Não está conseguindo se conectar ao servidor de desenvolvimento ?

**Comment by a113f** [comment]
Pois é.. quando dou react-native run-android, na versão 4.4 dá um erro:

`Could not run abd reverse` ( terminal )
`unable to load script from assets 'index.android.bundle'` ( emulador )

**Comment by a113f** [comment]
Então.... Consegui ajeitar com os seguintes comandos:

mkdir android\app\src\main\assets

react-native bundle —platform android —dev false —entry-file index.js —bundle-output android/app/src/main/assets/index.android.bundle —assets-dest android/app/src/main/res

Caso alguém esteja com o mesmo problema, só fazer isso aí.
